import "./globals.css";
import Header from "@/components/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="relative h-screen overflow-hidden  bg-cover bg-center bg-no-repeat"
        style={{
          backgroundImage:
            "url('https://media.istockphoto.com/id/958693744/vector/abstract-red-light-trail-on-blue-background.jpg?s=612x612&w=0&k=20&c=zaklCkqKZFiZFGcOjasGZLopy_cgp7fyA1yXltxQGDc=')"
        }}
      >
        <div className="h-[100dvh] overflow-scroll pb-[100px]">
          <div className="absolute inset-0 bg-gray-900/100 backdrop-blur-3xl"></div>
          <div className="relative z-10">
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
